### ISSUE TITLE
[Epic] Fix bugs in plutus-combined-exe

### ISSUE THREAD

**Issue by bezirg** [input-output-hk/plutus#6157]
- [ ] Rename withA,withL,withN,withNT,  , printE,printED to better names
- [ ]  Fix the bug in uplctypecheck for Names: https://github.com/IntersectMBO/plutus/blob/master/plutus-core/executables/plutus/AnyProgram/Compile.hs#L241
- [x] #6457
- [ ] Add proper verbose message stderr tracking
- [ ] move to SingI typeclass and a Compilable typeclass
- [ ] Re-think the --pretty options. -p should be classic by default. Can we also have none?
- [ ] Provenance annotation is utterly broken, so it is disabled currently. Fix provenance and then try to reenable
- [x] PLC.compileTerm should have a `through typeCheckTerm`
- [ ] Fix the broken `plutus --stdin --debug` , because stdin stays open and that breaks brick
- [x] Run a final typecheck of the applied program (irregardless of whole-opt option)
- [ ] Fix `optAstT` laziness error in `plutus -v -O1 -x pir ex3.pir ex1.pir --whole-opt [--stdout]`
- [x] `plutus ex5_typed.uplc --run` (Error from the PLC compiler Variable 5 defined at () is redefined at ())
- [ ] Fix termZip (void term1 /= void term2)
- [x] `plutus -v ex1.pir -x tplc --stdout --run` vs `plutus -v ex1.pir -x tplc --run`
- [x] Fix the examples that should not succeed:
   + [x] `plutus ex2.tplc ex1.pir -x tplc --stdout --run`
   + [x] `plutus ex2.tplc ex1.tplc -x tplc --whole-opt --run`
- [x] Fix self-opt that did not work, even with whole-opt:  `plutus -O1 ex6.tplc -x uplc --stdout`
- [ ] Add --run=save option
- [x] Implement  Data as Input
- [ ] Implement  JSON as Input
- [ ] Fix examples that are currently broken
- [ ] Port the debugger CLI from the older executable
- [ ] Build an exe for each release, and add it to release page ask @zeme-wana 
- [ ] Add Kenneth's new functionality
- [ ] Add Ana's metatheory new functionaly
- [ ] The plutus syntax version is fixed to 1.1.0 in AnyProgram/Compile.hs making 1.0.0 fail to compile
- [ ] Option to supply specific BuiltinSemanticVariant? 
- [x] Append a newline iff stdout and is textual
- [ ] All examples are broken at readProgram
- [ ] Figure out what constitutes -O0 , -O1 and -O2 optimization flags
- [ ] Graceful handling of no such file or directory
- [x] AnyProgram/Compile does more TC than needed (if we assume that PIR/PLC compilers are type preserving)
- [ ] Make --stdout default?
- [ ] What should be the .data-txt format? Right now it is `Show Data`
- [ ] "pretty" bug in `plutus ex2.pir-flat -p classic -x tplc -n debruijn --stdout`
- [ ] Support feeding custom cost model?
- [ ] Used budget is not printed in case of failure
- [ ] name of stdin file
- [ ] i think the `.*-cbor` extensions do not take the double enveloping into account. It would make more sense if they did.
